CREATE DATABASE oflixo;
USE oflixo;

CREATE TABLE userss (
	id INT AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(45) NOT NULL,
	email VARCHAR(155) NOT NULL UNIQUE,
	senha VARCHAR(45) NOT NULL
);

ALTER TABLE userss ADD COLUMN imagem_perfil VARCHAR(255);